# Generated by Django 3.1.4 on 2021-04-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=50, verbose_name='Цена')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='Район')),
                ('totalarea', models.CharField(blank=True, max_length=50, verbose_name='Общая площадь')),
                ('distancesea', models.CharField(blank=True, max_length=50, verbose_name='Расстояние до море')),
                ('distancetrack', models.CharField(blank=True, max_length=50, verbose_name='Расстояние до трассы')),
                ('vip', models.CharField(blank=True, choices=[('1', 'Нет'), ('2', 'Да')], default='1', max_length=10, verbose_name='Сделать VIP:')),
                ('ownership', models.CharField(blank=True, max_length=50, verbose_name='Право собственности')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Основные характеристики',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'города',
                'verbose_name_plural': 'Город',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Состояние',
                'verbose_name_plural': 'Состояние',
            },
        ),
        migrations.CreateModel(
            name='Leaseterms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Тип аренды')),
            ],
            options={
                'verbose_name': 'Тип аренды',
                'verbose_name_plural': 'Тип аренды',
            },
        ),
        migrations.CreateModel(
            name='Typehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Состояние',
                'verbose_name_plural': 'Состояние',
            },
        ),
        migrations.CreateModel(
            name='Typesale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='тип')),
            ],
            options={
                'verbose_name': 'Тип продажи',
                'verbose_name_plural': 'тип',
            },
        ),
        migrations.CreateModel(
            name='TypesApartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'недвижимости',
                'verbose_name_plural': 'Тип недвижимости',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='prjimages/%Y/%m/%d/%H/%M/%S/')),
                ('image_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.announcement')),
            ],
            options={
                'verbose_name': 'картинку',
                'verbose_name_plural': 'Все картинки',
            },
        ),
        migrations.CreateModel(
            name='Plots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.announcement', verbose_name='Главная информация')),
            ],
            options={
                'verbose_name': 'Участки',
                'verbose_name_plural': 'Участок',
            },
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('floor', models.CharField(blank=True, max_length=60, verbose_name='Кол-во этажей')),
                ('rooms', models.CharField(blank=True, max_length=60, verbose_name='Кол-во комнат')),
                ('house_area', models.CharField(blank=True, max_length=60, verbose_name='Площадь дома')),
                ('ceiling_height', models.CharField(blank=True, max_length=60, verbose_name='Высота потолков')),
                ('year_construction', models.CharField(blank=True, max_length=60, verbose_name='Высота потолков')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.announcement', verbose_name='Главная информация')),
                ('condition', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.condition', verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
        migrations.CreateModel(
            name='Commerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Заголовок (тип назначение)')),
                ('floor', models.CharField(blank=True, max_length=60, verbose_name='Этажность здания')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.announcement', verbose_name='Главная информация')),
                ('condition', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.condition', verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Коммерческая недвижимость',
                'verbose_name_plural': 'Коммерческая недвижимость',
            },
        ),
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('floor', models.CharField(blank=True, max_length=60, verbose_name='Этаж/этажность')),
                ('year_construction', models.CharField(blank=True, max_length=60, verbose_name='Высота потолков')),
                ('rooms', models.CharField(blank=True, max_length=60, verbose_name='Кол-во комнат')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.announcement', verbose_name='Главная информация')),
                ('condition', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.condition', verbose_name='Состояние')),
                ('type_house', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.typehouse', verbose_name='Тип дома')),
            ],
            options={
                'verbose_name': 'Квартиры',
                'verbose_name_plural': 'Квартира',
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='cities',
            field=models.ForeignKey(blank=True, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='main.cities', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='leaseterms',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.leaseterms', verbose_name='Длительно/Посуточно (аренда)'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='typesale',
            field=models.ForeignKey(blank=True, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='main.typesale', verbose_name='Продажа / Аренда'),
        ),
    ]
