# Generated by Django 3.1.4 on 2021-04-26 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_typesmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='type_material',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='main.typesmaterial', verbose_name='Тип материала'),
        ),
    ]
