# Generated by Django 3.1.4 on 2021-05-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210428_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='description',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Описание'),
        ),
    ]
